name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tox (code format check, tests, coverage report and check)
        run: |
          pip install -r requirements-dev.txt -r requirements.txt
          tox

      - uses: codecov/codecov-action@v3
        name: Codecov
        with:
          files: ./coverage.xml
